version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - '8080:8080'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: yarn run start:dev

volumes:
  pgdata:
